swagger: "2.0"
info:
  version: "1.0.0"
  title: "iMarts Customer Side API"
  contact:
    email: "babula@imarts.co"
host: "804vp22bk4.execute-api.ap-northeast-1.amazonaws.com"
tags:
- name: "Authroization"
  description: "APIs used for registering and logging in user"
- name: "Coming Soon"
  description: "There API is not implemented yet. Please come back later"

schemes:
- "https"

paths:
  /api/login/google:
    post:
      tags:
      - "Authroization"
      summary: "Log in with Google credentials"
      description: "Customers can log in iMarts APP with Google credentials."
      operationId: "googleLogin"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "ID token retrieved from Google OAuth service"
        required: true
        schema:
          $ref: "#/definitions/LoginWithOAuth"
      responses:
        "406":
          description: "Account does not exist. Please use google register API to create the account."
        "401":
          description: "invalid token"
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "Successfully log in with Google credentials."

  /api/register/google:
    post:
      tags:
      - "Authroization"
      summary: "Register a new account with Google credentials"
      description: "Customers can register a new account with Google credentials."
      operationId: "googleRegister"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer info for creating a new account."
        required: true
        schema:
          $ref: "#/definitions/RegisterWithOAuth"
      responses:
        "409":
          description: "Customer account with spcified Google ID already exists"
        "401":
          description: "invalid token"
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "Account is created Successfully"
  
  /api/login/facebook:
    post:
      tags:
      - "Coming Soon"
      summary: "Log in with Facebook credentials"
      description: "Customers can log in iMarts APP with Facebook credentials."
      operationId: "facebookLogin"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Access token retrieved from Facebook OAuth service"
        required: true
        schema:
          $ref: "#/definitions/LoginWithOAuth"
      responses:
        "406":
          description: "Account does not exist. Please use facebook register API to create the account."
        "200":
          description: "Successfully log in with Facebook credentials."

  /api/register/facebook:
    post:
      tags:
      - "Coming Soon"
      summary: "Register a new account with Facebook credentials"
      description: "Customers can register a new account with Facebook credentials."
      operationId: "facebookRegister"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer info for creating a new account."
        required: true
        schema:
          $ref: "#/definitions/RegisterWithOAuth"
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "409":
          description: "Customer account with spcified Facebook ID already exists"
        "200":
          description: "Account is created Successfully"

  /api/login/mail:
    post:
      tags:
      - "Authroization"
      summary: "Log in with email"
      description: "Customers can log in iMarts APP with email."
      operationId: "mailLogin"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/LoginWithMail"
      responses:
        "406":
          description: "Account does not exist."
        "401":
          description: "wrong credential"
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "Successfully log in with email."

  /api/register/mail:
    post:
      tags:
      - "Authroization"
      summary: "Register a new account with email"
      description: "Customers can register a new account with email."
      operationId: "mailRegister"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer info for creating a new account."
        required: true
        schema:
          $ref: "#/definitions/RegisterWithMail"
      responses:
        "406":
          description: "Account does not exist."
        "401":
          description: "Unmatched PIN"
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "Account is created Successfully"

  /api/pin/request:
    post:
      tags:
      - "Authroization"
      operationId: 'requestPIN'
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/PINRequest"
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "PIN is sent via email"
  
  /api/pin/verify:
    post:
      tags:
      - "Authroization"
      operationId: "verifyPIN"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/PINVerify"
      responses:
        "406":
          description: "account not found"
        "401":
          description: "Unmatched PIN"
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "Email account is verified"

  /api/region/dial-code:
    get:
      tags:
      - "Authroization"
      summary: "Get country dial code list"
      operationId: "dialCode"
      parameters:
      - name: "lang"
        in: "query"
        type: string
        enum:
          - en-us
          - zh-tw
          - ja
          - ko
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"

  /api/region/subregions:
    get:
      tags:
      - "Authroization"
      summary: "Get subregion list of the specified region"
      operationId: "subregions"
      parameters:
      - name: "lang"
        in: "query"
        type: string
        required: true
        enum:
          - en-us
          - zh-tw
          - ja
          - ko
      - name: "level"
        in: "query"
        required: true
        type: string
        enum:
          - country
          - level1
          - level2
      - name: "key"
        in: "query"
        required: true
        type: string
        description: "Key of the region. For country, use country code such as JPN, USA. For region of other levels, use id returned by backend."
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"


  /api/hashtag/hot:
    get:
      tags:
      - "Hashtag"
      summary: "Get popular hashtags"
      operationId: "hotHashtags"
      parameters:
      - name: "lang"
        in: "query"
        required: true
        type: string
        enum:
          - en-us
          - zh-tw
          - ja
          - ko
      - name: "latitude"
        in: "query"
        required: true
        type: "number"
        description: 'Example: 23.98'
      - name: "longitude"
        in: "query"
        required: true
        type: "number"
        description: 'Example: 121.6'
      - name: "type"
        in: "query"
        required: true
        type: "string"
        enum:
          - recommend
          - marketing
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"
 
  /api/hashtag/tagged:
    get:
      tags:
      - "Hashtag"
      summary: "Get items by hashtag"
      operationId: "hashtaggedItems"
      parameters:
      - name: "lang"
        in: "query"
        required: true
        type: string
        enum:
          - en-us
          - zh-tw
          - ja
          - ko
      - name: "latitude"
        in: "query"
        required: true
        type: "number"
        description: 'Example: 23.98'
      - name: "longitude"
        in: "query"
        required: true
        type: "number"
        description: 'Example: 121.6'
      - name: "hashtag"
        in: "query"
        required: true
        type: "string"
        description: 'Example: cd14a90a-3451-11eb-8aee-002b673caf83'
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"

  /api/store/info:
    get:
      tags:
      - "Store"
      summary: "Get all store info by id"
      operationId: "storeInfo"
      parameters:
      - name: "lang"
        in: "query"
        required: true
        type: string
        enum:
          - en-us
          - zh-tw
          - ja
          - ko
      - name: "latitude"
        in: "query"
        required: true
        type: "number"
        description: 'Example: 23.98'
      - name: "longitude"
        in: "query"
        required: true
        type: "number"
        description: 'Example: 121.6'
      - name: "id"
        in: "query"
        required: true
        type: "string"
        description: 'Example: 0003df6a-c5ba-4173-b38b-e34337'
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"

  /api/store/basic:
    get:
      tags:
      - "Store"
      summary: "Get store basic info by id"
      operationId: "storeBasic"
      parameters:
      - name: "lang"
        in: "query"
        required: true
        type: string
        enum:
          - en-us
          - zh-tw
          - ja
          - ko
      - name: "latitude"
        in: "query"
        required: true
        type: "number"
        description: 'Example: 23.98'
      - name: "longitude"
        in: "query"
        required: true
        type: "number"
        description: 'Example: 121.6'
      - name: "id"
        in: "query"
        required: true
        type: "string"
        description: 'Example: 0003df6a-c5ba-4173-b38b-e34337'
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"

  /api/store/category:
    get:
      tags:
      - "Store"
      summary: "Get store category by id"
      operationId: "storeCategory"
      parameters:
      - name: "lang"
        in: "query"
        required: true
        type: string
        enum:
          - en-us
          - zh-tw
          - ja
          - ko
      - name: "id"
        in: "query"
        required: true
        type: "string"
        description: 'Example: 0003df6a-c5ba-4173-b38b-e34337'
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"

  /api/store/open-hour:
    get:
      tags:
      - "Store"
      summary: "Get store open hour by id"
      operationId: "storeOpenHour"
      parameters:
      - name: "id"
        in: "query"
        required: true
        type: "string"
        description: 'Example: 0003df6a-c5ba-4173-b38b-e34337'
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"

  /api/store/price:
    get:
      tags:
      - "Store"
      summary: "Get store price level by id"
      operationId: "storePrice"
      parameters:
      - name: "id"
        in: "query"
        required: true
        type: "string"
        description: 'Example: 0003df6a-c5ba-4173-b38b-e34337'
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"

  /api/store/payment:
    get:
      tags:
      - "Store"
      summary: "Get supported payment method by store id"
      operationId: "storePayment"
      parameters:
      - name: "id"
        in: "query"
        required: true
        type: "string"
        description: 'Example: 00145046-346a-11eb-88de-002b673caf83'
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"

  /api/store/score:
    get:
      tags:
      - "Store"
      summary: "Get score summary by store id"
      operationId: "storeScore"
      parameters:
      - name: "id"
        in: "query"
        required: true
        type: "string"
        description: 'Example: df903286-f179-11ea-9410-58961d'
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"

  /api/store/comment:
    get:
      tags:
      - "Store"
      summary: "Get comments by store id"
      operationId: "storeComment"
      parameters:
      - name: "id"
        in: "query"
        required: true
        type: "string"
        description: 'Example: df903286-f179-11ea-9410-58961d'
      - name: "offset"
        in: "query"
        required: true
        type: number
        description: 'Used for fetching more comments'
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"

  /api/store/latest:
    get:
      tags:
      - "Store"
      summary: "Get latest store list"
      operationId: "latestStore"
      parameters:
        - name: "lang"
          in: "query"
          required: true
          type: string
          enum:
            - en-us
            - zh-tw
            - ja
            - ko
        - name: "latitude"
          in: "query"
          required: true
          type: "number"
          description: 'Example: 23.98'
        - name: "longitude"
          in: "query"
          required: true
          type: "number"
          description: 'Example: 121.6'
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "ok"

definitions:
  LoginWithOAuth:
    type: "object"
    required:
      - token
      - agent
    properties:
      agent:
        type: "string"
        enum:
        - android
        - ios
        - web
      token:
        type: "string"
  LoginWithMail:
    type: "object"
    required:
      - email
      - password
    properties:
      email:
        type: "string"
      password:
        type: "string"
  RegisterWithOAuth:
    type: "object"
    required:
      - agent
      - token
      - username
    properties:
      agent:
        type: "string"
        enum:
        - android
        - ios
        - web
      token:
        type: "string"
        description: "ID token or access token from the OAuth service"
      username:
        type: "string"
      birthday:
        type: "string"
        description: "YYYY/MM/DD"
      country:
        type: "string"
        description: 'Country code. Example: TWN'
      region:
        type: "number"
        description: 'Region ID responsed from backend'
      address:
        type: "string"
      dial-code:
        type: "string"
        description: 'Country dial code. Example: 886'
      phone:
        type: "string"
  RegisterWithMail:
    type: "object"
    required:
      - email
      - username
      - password
      - pin
    properties:
      email:
        type: "string"
      username:
        type: "string"
      password:
        type: "string"
      pin:
        type: "string"
        description: "Verification PIN"
      birthday:
        type: "string"
        description: "YYYY/MM/DD"
      country:
        type: "string"
        description: 'Country code. Example: TWN'
      region:
        type: "number"
        description: 'Region ID responsed from backend'
      address:
        type: "string"
      dial_code:
        type: "string"
        description: 'Country dial code. Example: 886'
      phone:
        type: "string"
  PINVerify:
    type: "object"
    required:
      - email
      - pin
    properties:
      email:
        type: "string"
      pin:
        type: "string"
  PINRequest:
    type: "object"
    required:
      - email
    properties:
      email:
        type: "string"
      lang:
        type: "string"
        enum:
        - zh-tw
        - en-us
        - ja
        - ko

        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
