swagger: "2.0"
info:
  version: "1.0.0"
  title: "iMarts Customer Side API"
  contact:
    email: "babula@imarts.co"
host: "r0vz5tq1m0.execute-api.ap-northeast-1.amazonaws.com"
tags:
- name: "Authroization"
  description: "APIs used for registering and logging in user"

schemes:
- "https"

paths:
  /api/login/google:
    post:
      tags:
      - "Authroization"
      summary: "Log in with Google credentials"
      description: "Customers can log in iMarts APP with Google credentials."
      operationId: "googleLogin"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "ID token retrieved from Google OAuth service"
        required: true
        schema:
          $ref: "#/definitions/LoginWithOAuth"
      responses:
        "406":
          description: "Account does not exist. Please use google register API to create the account."
        "401":
          description: "invalid token"
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "Successfully log in with Google credentials."

  /api/register/google:
    post:
      tags:
      - "Authroization"
      summary: "Register a new account with Google credentials"
      description: "Customers can register a new account with Google credentials."
      operationId: "googleRegister"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer info for creating a new account."
        required: true
        schema:
          $ref: "#/definitions/RegisterWithOAuth"
      responses:
        "409":
          description: "Customer account with spcified Google ID already exists"
        "401":
          description: "invalid token"
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "Account is created Successfully"
  
  /api/login/facebook:
    post:
      tags:
      - "Authroization"
      summary: "Log in with Facebook credentials"
      description: "Customers can log in iMarts APP with Facebook credentials."
      operationId: "facebookLogin"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Access token retrieved from Facebook OAuth service"
        required: true
        schema:
          $ref: "#/definitions/LoginWithOAuth"
      responses:
        "406":
          description: "Account does not exist. Please use facebook register API to create the account."
        "200":
          description: "Successfully log in with Facebook credentials."

  /api/register/facebook:
    post:
      tags:
      - "Authroization"
      summary: "Register a new account with Facebook credentials"
      description: "Customers can register a new account with Facebook credentials."
      operationId: "facebookRegister"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer info for creating a new account."
        required: true
        schema:
          $ref: "#/definitions/RegisterWithOAuth"
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "409":
          description: "Customer account with spcified Facebook ID already exists"
        "200":
          description: "Account is created Successfully"

  /api/login/email:
    post:
      tags:
      - "Authroization"
      summary: "Log in with email"
      description: "Customers can log in iMarts APP with email."
      operationId: "emailLogin"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/LoginWithEmail"
      responses:
        "406":
          description: "Account does not exist."
        "401":
          description: "wrong credential"
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "Successfully log in with email."

  /api/register/email:
    post:
      tags:
      - "Authroization"
      summary: "Register a new account with email"
      description: "Customers can register a new account with email."
      operationId: "emailRegister"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer info for creating a new account."
        required: true
        schema:
          $ref: "#/definitions/RegisterWithEmail"
      responses:
        "406":
          description: "Account does not exist."
        "401":
          description: "Unmatched PIN"
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "Account is created Successfully"

  /api/pin/request:
    post:
      tags:
      - "Authroization"
      operationId: 'requestPIN'
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/PINRequest"
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "PIN is sent via email"
  
  /api/pin/verify:
    post:
      tags:
      - "Authroization"
      operationId: "verifyPIN"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/PINVerify"
      responses:
        "406":
          description: "account not found"
        "401":
          description: "Unmatched PIN"
        "400":
          description: "Required parameters is not included in request body"
        "200":
          description: "Email account is verified"
 

definitions:
  LoginWithOAuth:
    type: "object"
    required:
      - token
      - agent
    properties:
      agent:
        type: "string"
        enum:
        - android
        - ios
        - web
      token:
        type: "string"
  LoginWithEmail:
    type: "object"
    required:
      - username
      - password
    properties:
      username:
        type: "string"
      password:
        type: "string"
  RegisterWithOAuth:
    type: "object"
    required:
      - agent
      - token
      - username
    properties:
      agent:
        type: "string"
        enum:
        - android
        - ios
        - web
      token:
        type: "string"
        description: "ID token or access token from the OAuth service"
      username:
        type: "string"
      birthday:
        type: "string"
        description: "YYYY/MM/DD"
      address:
        type: "string"
      phone:
        type: "string"
  RegisterWithEmail:
    type: "object"
    required:
      - email
      - username
      - password
      - pin
    properties:
      email:
        type: "string"
      username:
        type: "string"
      password:
        type: "string"
      pin:
        type: "string"
        description: "Verification PIN"
      birthday:
        type: "string"
        description: "YYYY/MM/DD"
      address:
        type: "string"
      phone:
        type: "string"
  PINVerify:
    type: "object"
    required:
      - email
      - pin
    properties:
      email:
        type: "string"
      pin:
        type: "string"
  PINRequest:
    type: "object"
    required:
      - email
    properties:
      email:
        type: "string"
      lang:
        type: "string"
        enum:
        - zh-tw
        - en
        - jp
        - ko

        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
