swagger: "2.0"
info:
  version: "1.0.0"
  title: "iMarts Customer Side API"
  contact:
    email: "babula@imarts.co"
host: "r0vz5tq1m0.execute-api.ap-northeast-1.amazonaws.com"                                                               "
tags:
- name: "Authroization"
  description: "APIs used for registering and logging in user"

schemes:
- "https"

paths:
  /api/login/google:
    post:
      tags:
      - "Authroization"
      summary: "Log in with Google credentials"
      description: "Customers can log in iMarts APP with Google credentials."
      operationId: "googleLogin"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "ID token retrieved from Google OAuth service"
        required: true
        schema:
          $ref: "#/definitions/LoginWithOAuth"
      responses:
        "406":
          description: "Account does not exist. Please use google register API to create the account."
        "200":
          description: "Successfully log in with Google credentials."

  /api/register/google:
    post:
      tags:
      - "Authroization"
      summary: "Register a new account with Google credentials"
      description: "Customers can register a new account with Google credentials."
      operationId: "googleRegister"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer info for creating a new account."
        required: true
        schema:
          $ref: "#/definitions/RegisterWithOAuth"
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "409":
          description: "Customer account with spcified Google ID already exists"
        "200":
          description: "Account is created Successfully"
  
  /api/login/facebook:
    post:
      tags:
      - "Authroization"
      summary: "Log in with Facebook credentials"
      description: "Customers can log in iMarts APP with Facebook credentials."
      operationId: "facebookLogin"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Access token retrieved from Facebook OAuth service"
        required: true
        schema:
          $ref: "#/definitions/LoginWithOAuth"
      responses:
        "406":
          description: "Account does not exist. Please use facebook register API to create the account."
        "200":
          description: "Successfully log in with Facebook credentials."

  /api/register/facebook:
    post:
      tags:
      - "Authroization"
      summary: "Register a new account with Facebook credentials"
      description: "Customers can register a new account with Facebook credentials."
      operationId: "facebookRegister"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer info for creating a new account."
        required: true
        schema:
          $ref: "#/definitions/RegisterWithOAuth"
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "409":
          description: "Customer account with spcified Facebook ID already exists"
        "200":
          description: "Account is created Successfully"

  /api/login/email:
    post:
      tags:
      - "Authroization"
      summary: "Log in with email"
      description: "Customers can log in iMarts APP with email."
      operationId: "emailLogin"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/LoginWithEmail"
      responses:
        "406":
          description: "Account does not exist."
        "200":
          description: "Successfully log in with email."

  /api/register/email:
    post:
      tags:
      - "Authroization"
      summary: "Register a new account with email"
      description: "Customers can register a new account with email."
      operationId: "emailRegister"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer info for creating a new account."
        required: true
        schema:
          $ref: "#/definitions/RegisterWithEmail"
      responses:
        "400":
          description: "Required parameters is not included in request body"
        "409":
          description: "Customer account with spcified email already exists"
        "200":
          description: "Account is created Successfully"

  /api/verify/request:
    get:
      tags:
      - "Authroization"
      operationId: 'verificationRequest'
      responses:
        "200":
          description: "Verification code is sent via email"
  
  /api/verify/submission:
    post:
      tags:
      - "Authroization"
      operationId: "verificationResult"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/EmailVerification"
      responses:
        "200":
          description: "Email account is verified"
          schema:
            type: "object"
            properties:
              match:
                type: "boolean"
 

definitions:
  LoginWithOAuth:
    type: "object"
    required:
      - token
      - agent
    properties:
      agent:
        type: "string"
        enum:
        - android
        - ios
        - web
      token:
        type: "string"
  LoginWithEmail:
    type: "object"
    required:
      - username
      - password
    properties:
      username:
        type: "string"
      password:
        type: "string"
  RegisterWithOAuth:
    type: "object"
    required:
      - email
      - id
      - username
    properties:
      agent:
        type: "string"
        enum:
        - android
        - ios
        - web
      token:
        type: "string"
        description: "ID token or access token from the OAuth service"
      username:
        type: "string"
      birthday:
        type: "string"
        description: "YYYY/MM/DD"
      address:
        type: "string"
      phone:
        type: "string"
  RegisterWithEmail:
    type: "object"
    required:
      - email
      - username
      - password
      - code
    properties:
      email:
        type: "string"
      username:
        type: "string"
      password:
        type: "string"
      code:
        type: "string"
        description: "Verification code."
      birthday:
        type: "string"
        description: "YYYY/MM/DD"
      address:
        type: "string"
      phone:
        type: "string"
  EmailVerification:
    type: "object"
    required:
      - email
      - code
    properties:
      email:
        type: "string"
      code:
        type: "string"
        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
